name: PHP Checks

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Validate Composer file
        working-directory: httpdocs
        run: composer validate --no-check-publish

      - name: Lint PHP files
        shell: bash
        run: |
          while IFS= read -r file; do
            php -l "$file"
          done < <(find app.axet.fr auth.axet.fr admin.axet.fr api.axet.fr docs.axet.fr cdn.axet.fr httpdocs -type f -name "*.php")
